version: 2
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install python3 python3-pip git python3-pil python3-pil.imagetk -y
      - run: python3 --version